// MOVIES
export const GET_MOVIES_LIST = "GET_MOVIES_LIST";
export const CLEAR_MOVIES_LIST = "CLEAR_MOVIES_LIST";
export const GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST";
export const GET_MOVIE_BY_CATEGORY = "GET_MOVIE_BY_CATEGORY";
export const GET_RANDOM_MOVIE = "GET_RANDOM_MOVIE";
export const GET_MOVIE_POSTER = "GET_MOVIE_POSTER";
export const GET_INFOS_MOVIE = "GET_INFOS_MOVIE";
export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const SEARCH_MOVIE_TO_ADD = "SEARCH_MOVIE_TO_ADD";
export const SEARCH_MOVIE_IN_COLLECTION = "SEARCH_MOVIE_IN_COLLECTION";

// AUTH
export const UPDATE_FORM_SIGN_IN = "UPDATE_FORM_SIGN_IN";
export const UPDATE_FORM_SIGN_UP = "UPDATE_FORM_SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const SIGN_OUT = "SIGN_OUT";
export const GET_PROFILE_FETCH = "GET_PROFILE_FETCH";

