export const GET_MOVIES_LIST = "GET_MOVIES_LIST";
export const GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST";
export const GET_MOVIE_BY_CATEGORY = "GET_MOVIE_BY_CATEGORY";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const GET_RANDOM_MOVIE = "GET_RANDOM_MOVIE";
export const GET_MOVIE_BY_NAME = "GET_MOVIE_BY_NAME";
export const GET_POSTER_MOVIE = "GET_POSTER_MOVIE";


